--Suppression des toutes les tables de l'utilisateurs
BEGIN
    FOR c IN (SELECT object_name,
                     object_type
              FROM user_objects
              WHERE object_type IN ('TABLE') AND object_name NOT LIKE '%$%') LOOP
        EXECUTE IMMEDIATE 'DROP '
                             || c.object_type || ' "'
                             || c.object_name || '" CASCADE CONSTRAINTS';
    END LOOP;
END;










  CURSOR listeLivre IS   SELECT PROD_NOM, PROD_DESCRIPTION FROM PRODUIT
  INNER JOIN LIVRE ON LIVRE.PRODUIT_PROD_ID=PRODUIT.PROD_ID
  INNER JOIN EDITEUR ON EDITEUR.EDIT_ID=LIVRE.EDITEUR_EDIT_ID
  INNER JOIN GENRE ON GENRE.GENRE_ID=LIVRE.GENRE_GENRE_ID
  WHERE PROD_ID IN (
    SELECT PRODUIT_prod_id FROM Livre
  );



  CREATE OR REPLACE PROCEDURE meilleuresVentes()
  IS 
  BEGIN
  END;

  #REQUETE HISTORIQUE COMMANDE
SELECT FROM PANIER
INNER JOIN COMMANDE ON COMMANDE.PANIER_PANIER_ID=PANIER.PANIER_ID
WHERE PANIER.PANIER_ID IN (SELECT COMMANDE.PANIER_PANIER_ID FROM COMMANDE) AND PANIER.CLIENT_CLI_ID = 1
ORDER BY COMMANDE_DATE DESC;